#!/bin/sh

# Coffee-Manager v1.2.0

while [ "$returncheck" != "1" ]; do
#-Main-Menu
while [ "$updatecheck" != "1" ] && [ "$updatecheck" != "2" ] && [ "$updatecheck" != "3" ] && [ "$updatecheck" != "4" ] && [ "$updatecheck" != "5" ]; do 
printf "%b\n What would you like to do?\n" "$*"
printf "%b\n1 - Update the OS.\n" "$*"
printf "%b\n2 - Update Snap-Store Apps.\n" "$*"
printf "%b\n3 - View OS Information.\n" "$*"
printf "%b\n4 - Install an Application.\n" "$*"
printf "%b\n5 - Uninstall an Application.\n" "$*"
read -r updatecheck
case $updatecheck in
  1) printf "%b\nYay for OS updates.\n" "$*" ;;
  2) printf "%b\nYay for Snap updates.\n" "$*" ;;
  3) printf "%b\nCheckin the specs..\n" "$*" ;;
  4) printf "%b\nLet's install something..\n" "$*" ;;
  5) printf "%b\nLet's uninstall something..\n" "$*" ;;
  *) printf "%b\nUnrecognized option, please try again.\n" "$*" ;;
esac
done

if [ "$updatecheck" = "1" ]; then
sudo pacman -Syu
exit
elif [ "$updatecheck" = "2" ]; then
sudo snap refresh
exit
elif [ "$updatecheck" = "3" ]; then
neofetch
exit
elif [ "$updatecheck" = "4" ]; then
#
#-Application-Installer
printf "%b\n2 - Application Installer Starting...\n" "$*"
while [ "$appnamecheck" != "1" ]; do 
printf "%b\n What application would you like to install\n" "$*"
read -r appname
printf "%b\n$appname.\n Is this correct?\n" "$*"
printf "%b\n1 - yes\n" "$*"
printf "%b\n2 - no\n" "$*"
read -r appnamecheck
case $appnamecheck in
  1) printf "%b\nPerfect\n" "$*" ;;
  *) printf "%b\nLet's retry\n" "$*" ;;
  #*) printf "%b\nUnrecognized option, please try again: $user00\n" "$*" ;;
esac
done
if [ "$appnamecheck" = "1" ]; then 
app01=$appname
fi
while [ "$paknamecheck" != "1" ] && [ "$paknamecheck" != "2" ] && [ "$paknamecheck" != "3" ]; do 
printf "%b\n Which package manager should install it?\n" "$*"
printf "%b\n1 - Pacman\n" "$*"
printf "%b\n2 - Yay/AUR\n" "$*"
printf "%b\n3 - Snap\n" "$*"
read -r paknamecheck

if [ "$paknamecheck" = "1" ]; then
pakname="Ahh.. good ol Pacman.\n"
elif [ "$paknamecheck" = "2" ]; then
pakname="Yay is good.\n"
elif [ "$paknamecheck" = "3" ]; then
pakname="Snap it is.\n"
fi
#
case $paknamecheck in
  1) printf "%b\n$pakname\n" "$*" ;;
  2) printf "%b\n $pakname\n" "$*" ;;
  3) printf "%b\n$pakname\n" "$*" ;;
  *) printf "%b\nUnrecognized option\n" "$*" ;;
esac
done
if [ "$paknamecheck" = "1" ]; then 
sudo pacman -Sy "$app01"
exit
elif [ "$paknamecheck" = "2" ]; then
yay --nodiffmenu --noremovemake --answerclean a  --answerdiff n --answeredit y --answerupgrade y "$app01"
exit
elif [ "$paknamecheck" = "3" ]; then
sudo snap install "$app01"
exit
fi
#End Application- Installer

elif [ "$updatecheck" = "5" ]; then

#-Application-Uninstaller
printf "%b\n2 - Application Uninstaller Starting...\n" "$*"
while [ "$appnamecheck" != "1" ]; do 
printf "%b\n What application would you like to uninstall\n" "$*"
read -r appname
printf "%b\n$appname.\n Is this correct?\n" "$*"
printf "%b\n1 - yes\n" "$*"
printf "%b\n2 - no\n" "$*"
read -r appnamecheck
case $appnamecheck in
  1) printf "%b\nPerfect\n" "$*" ;;
  *) printf "%b\nLet's retry\n" "$*" ;;
  #*) printf "%b\nUnrecognized option, please try again: $user00\n" "$*" ;;
esac
done
if [ "$appnamecheck" = "1" ]; then 
app01=$appname
fi
while [ "$paknamecheck" != "1" ] && [ "$paknamecheck" != "2" ] && [ "$paknamecheck" != "3" ]; do 
printf "%b\n Which package manager should uninstall it?\n" "$*"
printf "%b\n1 - Pacman\n" "$*"
printf "%b\n2 - Yay/AUR\n" "$*"
printf "%b\n3 - Snap\n" "$*"
read -r paknamecheck

if [ "$paknamecheck" = "1" ]; then
pakname="Ahh.. good ol Pacman.\n"
elif [ "$paknamecheck" = "2" ]; then
pakname="Yay is good.\n"
elif [ "$paknamecheck" = "3" ]; then
pakname="Snap it is.\n"
fi
#
case $paknamecheck in
  1) printf "%b\n$pakname\n" "$*" ;;
  2) printf "%b\n $pakname\n" "$*" ;;
  3) printf "%b\n$pakname\n" "$*" ;;
  *) printf "%b\nUnrecognized option\n" "$*" ;;
esac
done
if [ "$paknamecheck" = "1" ]; then 
sudo pacman -R "$app01"
exit
elif [ "$paknamecheck" = "2" ]; then
yay --remove "$app01"
exit
elif [ "$paknamecheck" = "3" ]; then
sudo snap remove "$app01"
exit
fi

#End Application- Uninstaller

fi
printf "%b\n Would you like to return to the Main Menu?\n" "$*"
printf "%b\n1 - No\n" "$*"
printf "%b\n2 - Yes\n" "$*"
read -r returncheck
case $returncheck in
  1) printf "%b\nExiting\n" "$*" ;;
  2) printf "%b\nReturning to Main..\n" "$*" ;;
  #3) printf "%b\n$pakname\n" "$*" ;;
  *) printf "%b\nUnrecognized option\n" "$*" ;;
esac
if [ "$returncheck" = "1" ]; then 
echo ""
elif [ "$returncheck" = "2" ]; then
echo ""
fi

done
#-End-Script
exit


